# Generated by Django 5.2.5 on 2025-08-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=50, unique=True)),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
