# Generated by Django 5.2.6 on 2025-09-15 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auditlog_employee_birth_date_employee_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('certifier_requested', models.CharField(choices=[('punong_barangay', 'Punong Barangay'), ('dilg_municipality', 'DILG - Municipality'), ('dilg_provincial', 'DILG - Provincial'), ('dilg_regional', 'DILG - Regional')], max_length=50)),
                ('id_front', models.ImageField(upload_to='eligibility_requests/ids/')),
                ('id_back', models.ImageField(upload_to='eligibility_requests/ids/')),
                ('signature', models.ImageField(upload_to='eligibility_requests/signatures/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eligibility Request',
                'verbose_name_plural': 'Eligibility Requests',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
