# Generated by Django 5.2.6 on 2025-09-15 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_eligibilityrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eligibilityrequest',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.RenameField(
            model_name='eligibilityrequest',
            old_name='certifier_requested',
            new_name='certifier',
        ),
        migrations.RemoveField(
            model_name='eligibilityrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='eligibilityrequest',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='eligibilityrequest',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eligibilityrequest',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='eligibility/ids/'),
        ),
        migrations.AlterField(
            model_name='eligibilityrequest',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='eligibility/ids/'),
        ),
        migrations.AlterField(
            model_name='eligibilityrequest',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilityrequest',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='eligibility/signatures/'),
        ),
        migrations.AlterField(
            model_name='eligibilityrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
    ]
