# Generated by Django 5.2.6 on 2025-09-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_eligibilityrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrequest',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
