# Generated by Django 5.2.7 on 2025-10-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_eligibilityrequest_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('barangay official', 'Barangay Official'), ('municipal officer', 'Municipal Officer'), ('dilg staff', 'DILG Staff')], max_length=50),
        ),
    ]
