# Generated by Django 5.2.7 on 2025-10-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
