# Generated by Django 5.2.7 on 2025-10-23 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_announcement_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('reminder', 'Reminder'), ('info', 'Info')], default='info', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='app_notific_user_id_5559cb_idx'),
        ),
    ]
