# Generated by Django 5.2.7 on 2025-10-23 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_notification_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='app_notific_user_id_5559cb_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.announcement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.barangay'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('reminder', 'Reminder'), ('info', 'Information'), ('announcement', 'Announcement')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.requirementsubmission'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
