# Generated by Django 5.2.7 on 2025-11-03 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_notification_app_notific_user_id_5559cb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('certificates', 'Certificates'), ('ids', 'Identification Documents'), ('signatures', 'Signatures'), ('weekly', 'Weekly Reports'), ('monthly', 'Monthly Reports'), ('quarterly', 'Quarterly Reports'), ('semestral', 'Semestral Reports'), ('annually', 'Annual Reports'), ('general', 'General Documents')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('folder_path', models.CharField(max_length=200)),
                ('icon', models.CharField(default='fa-folder', max_length=50)),
                ('file_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'File Category',
                'verbose_name_plural': 'File Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategorizedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='categorized/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF Document'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('eligibility', 'Eligibility Request'), ('requirement', 'Requirement Submission'), ('manual', 'Manual Upload')], max_length=20)),
                ('detected_content', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(blank=True, max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.barangay')),
                ('eligibility_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorized_files', to='app.eligibilityrequest')),
                ('requirement_attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorized_file', to='app.requirementattachment')),
                ('requirement_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorized_files', to='app.requirementsubmission')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.filecategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['category', 'uploaded_at'], name='app_categor_categor_57ff32_idx'), models.Index(fields=['barangay', 'period'], name='app_categor_baranga_398623_idx'), models.Index(fields=['source', 'file_type'], name='app_categor_source_99fb7a_idx')],
            },
        ),
    ]
