# Generated by Django 5.2.6 on 2025-11-05 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_filecategory_categorizedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='monitoring_files/')),
                ('category', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barangay')),
            ],
        ),
    ]
