# Generated by Django 5.2.8 on 2025-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_monitoringfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrequest',
            name='barangay',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='position_type',
            field=models.CharField(choices=[('appointive', 'Appointive'), ('elective', 'Elective')], default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
