# Generated by Django 5.2.8 on 2025-11-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_eligibilityrequest_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrequest',
            name='appointing_authority',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='appointing_punong_barangay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='appointment_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='appointment_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='completed_term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='days_not_served',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='election_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='election_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='incomplete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='pb_date_elected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='pb_years_service',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='position_held',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='term_office',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrequest',
            name='years_in_service',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
