# Generated by Django 5.2.8 on 2025-11-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_eligibilityrequest_appointing_authority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityrequest',
            name='days_not_served',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eligibilityrequest',
            name='signature',
            field=models.FileField(upload_to='certification_files/signatures/%Y/%m/'),
        ),
    ]
