# Generated by Django 5.2.8 on 2025-11-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_employee_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrequest',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
